kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webrtc-pvc
  namespace: webrtc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
