kind: PersistentVolume
apiVersion: v1
metadata:
  name: webrtc-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: webrtc
    name: webrtc-pvc
  hostPath:
    path: "/mnt/webrtc_data"